{
 "title": "orderacknowledgement-SpringService-Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_uptime_seconds{application=\"orderacknowledgement\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_start_time_seconds{application=\"orderacknowledgement\"}*1000)"
    }
   ]
  },
  {
   "title": "Average Response Time (since time selected)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_sum{application=\"orderacknowledgement\", method=\"POST\", uri!=\"/actuator/prometheus\"}[$__range]))/sum(increase(http_server_requests_seconds_count{application=\"orderacknowledgement\", method=\"POST\", uri!=\"/actuator/prometheus\"}[$__range]))*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"orderacknowledgement\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"orderacknowledgement\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"orderacknowledgement\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"orderacknowledgement\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"orderacknowledgement\", method=\"POST\", uri!=\"/actuator/prometheus\"}[30s]))"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live{application=\"orderacknowledgement\"} or jvm_threads_live_threads{application=\"orderacknowledgement\"}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 11, "x": 13, "y": 3 } },
  {
   "title": "Response Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"orderacknowledgement\", method=\"POST\", uri!=\"/actuator/prometheus\"}[30s]))/sum(rate(http_server_requests_seconds_count{application=\"orderacknowledgement\", method=\"POST\", uri!=\"/actuator/prometheus\"}[30s]))*1000"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"orderacknowledgement\", uri!=\"/actuator/prometheus\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live{application=\"orderacknowledgement\"} or jvm_threads_live_threads{application=\"orderacknowledgement\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon{application=\"orderacknowledgement\"} or jvm_threads_daemon_threads{application=\"orderacknowledgement\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{application=\"orderacknowledgement\"} or jvm_threads_peak_threads{application=\"orderacknowledgement\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{application=\"orderacknowledgement\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Success Responses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"orderacknowledgement\", uri!=\"/actuator/prometheus\", outcome=\"SUCCESS\"}[$__range]))\n"
    },
    {}
   ]
  },
  {
   "title": "Response Latency Percentile",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "avg(orderacknowledgement_response_timer_seconds{quantile=\"0.5\"}*1000>0)",
     "legendFormat": "50th Percentile or Mean"
    },
    {
     "expr": "avg(orderacknowledgement_response_timer_seconds{quantile=\"0.75\"}*1000>0)",
     "legendFormat": "75th Percentile"
    },
    {
     "expr": "avg(orderacknowledgement_response_timer_seconds{quantile=\"0.8\"}*1000>0)",
     "legendFormat": "80th Percentile"
    },
    {
     "expr": "avg(orderacknowledgement_response_timer_seconds{quantile=\"0.9\"}*1000>0)",
     "legendFormat": "90th Percentile"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"orderacknowledgement\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Error Responses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"orderacknowledgement\", uri!=\"/actuator/prometheus\", outcome=\"SERVER_ERROR\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Successes vs. Error Responses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "HTTP Requests" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"orderacknowledgement\", uri!=\"/actuator/prometheus\", outcome=\"SUCCESS\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"orderacknowledgement\", outcome=\"SERVER_ERROR\"}[1m])",
     "legendFormat": "Server Error"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"orderacknowledgement\", outcome=\"CLIENT_ERROR\"}[1m])",
     "legendFormat": "Client Error"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"orderacknowledgement\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{application=\"orderacknowledgement\"}",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"orderacknowledgement\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit", "label": "CPU Percentage" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"orderacknowledgement\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{application=\"orderacknowledgement\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"orderacknowledgement\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"orderacknowledgement\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"orderacknowledgement\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"orderacknowledgement\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{application=\"orderacknowledgement\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"orderacknowledgement\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"orderacknowledgement\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"orderacknowledgement\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Heap Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"orderacknowledgement\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"orderacknowledgement\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Log Events (1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"orderacknowledgement\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}